version: '3'
services:
  db:
    image: "postgres:14.1"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - config.env

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - './data/redis:/data'

  app:
    build: .
    command: ./utils/entrypoint.sh
    env_file:
      - config.env
    ports:
      - 5123:5123
    volumes:
      - "./data/uploads:/var/cdb/uploads"
      - "./app:/source/app"
      - "./migrations:/source/migrations"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.tasks.celery worker
    env_file:
      - config.env
    environment:
      - FLASK_CONFIG=../config.cfg
    volumes:
      - "./data/uploads:/var/cdb/uploads"
      - "./app:/home/cdb/app"
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A app.tasks.celery beat
    env_file:
      - config.env
    environment:
      - FLASK_CONFIG=../config.cfg
    depends_on:
      - redis

  exporter:
    image: ovalmoney/celery-exporter
    env_file:
      - config.env
    ports:
      - 5125:9540
    depends_on:
      - redis
